# Generated by Django 5.1.5 on 2025-01-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('admin', 'Admin')], default='none', max_length=20, null=True),
        ),
    ]
